parser: vue-eslint-parser
parserOptions:
  parser: '@typescript-eslint/parser'
extends:
  - plugin:@typescript-eslint/recommended
  - plugin:vue/vue3-recommended
rules:
  '@typescript-eslint/explicit-module-boundary-types': 'off'
  vue/html-self-closing:
    - error
    - html:
        void: always
        normal: always
        component: always
  vue/singleline-html-element-content-newline: 'off'
  vue/attribute-hyphenation: 'off'
  vue/custom-event-name-casing: 'off'
