name: ウェブサイトのデプロイ
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - name: yarnのキャッシュディレクトリパスを取得
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Firebase CLIのインストール
        run: npm install -g firebase-tools
      - name: 依存関係のインストール
        run: yarn install --frozen-lockfile
      - name: アプリケーションのビルド
        run: |
          echo $VITE_GA_MEASUREMENT_ID
          yarn build
        env:
          VITE_GA_MEASUREMENT_ID: ${{ secrets.GA_MEASUREMENT_ID }}
      - name: Firebase Hostingへデプロイ
        run: firebase deploy --token $FIREBASE_TOKEN
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
